"""
Defines constants for constructing database schema.
"""


TITLE_TYPES = (
    'movie',
    'tv_show',
)


COUNTRIES = (
    'Afghanistan',
    'Albania',
    'Algeria',
    'Angola',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Bermuda',
    'Botswana',
    'Brazil',
    'Bulgaria',
    'Cambodia',
    'Canada',
    'Cayman Islands',
    'Chile',
    'China',
    'Colombia',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Dominican Republic',
    'East Germany',
    'Ecuador',
    'Egypt',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Guatemala',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Latvia',
    'Lebanon',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malawi',
    'Malaysia',
    'Malta',
    'Mauritius',
    'Mexico',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Namibia',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Norway',
    'Pakistan',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Samoa',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'South Africa',
    'South Korea',
    'Soviet Union',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Thailand',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'West Germany',
    'Zimbabwe',
)


RATINGS = (
    'G',
    'NC-17',
    'NR',
    'PG',
    'PG-13',
    'R',
    'TV-14',
    'TV-G',
    'TV-MA',
    'TV-PG',
    'TV-Y',
    'TV-Y7',
    'TV-Y7-FV',
    'UR',
)
